/**
 * @File Name          : myclass.cls
 * @Description        : 
 * @Author             : ChangeMeIn@UserSettingsUnder.SFDoc
 * @Group              : 
 * @Last Modified By   : ChangeMeIn@UserSettingsUnder.SFDoc
 * @Last Modified On   : 6/12/2020, 4:49:00 PM
 * @Modification Log   : 
 * Ver       Date            Author      		    Modification
 * 1.0    5/29/2020   ChangeMeIn@UserSettingsUnder.SFDoc     Initial Version
**/
public with sharing class myclass {
    public myclass() {
system.debug('Test223232323232323');
    }
}