/**
 * @File Name          : NewDevoffClassforGit.cls
 * @Description        : 
 * @Author             : ChangeMeIn@UserSettingsUnder.SFDoc
 * @Group              : 
 * @Last Modified By   : ChangeMeIn@UserSettingsUnder.SFDoc
 * @Last Modified On   : 6/12/2020, 5:58:24 PM
 * @Modification Log   : 
 * Ver       Date            Author      		    Modification
 * 1.0    6/12/2020   ChangeMeIn@UserSettingsUnder.SFDoc     Initial Version
**/
public with sharing class NewDevoffClassforGit {
    public NewDevoffClassforGit() {
        system.debug('Test');
system.debug('Test');
system.debug('Test');
system.debug('Test');
system.debug('Test');
system.debug('Test');
system.debug('Test');
system.debug('Test');
system.debug('Test');system.debug('Test');
system.debug('Test');
system.debug('Test');
system.debug('Test');
system.debug('Test');
system.debug('Test');

    }
}
