/**
 * @File Name          : Vikas2.cls
 * @Description        : 
 * @Author             : ChangeMeIn@UserSettingsUnder.SFDoc
 * @Group              : 
 * @Last Modified By   : ChangeMeIn@UserSettingsUnder.SFDoc
 * @Last Modified On   : 4/25/2020, 10:54:20 PM
 * @Modification Log   : 
 * Ver       Date            Author                 Modification
 * 1.0    4/25/2020   ChangeMeIn@UserSettingsUnder.SFDoc     Initial Version
**/
public with sharing class Vikas2 {
    public Vikas2() {
system.debug('aaa');
    }
}